# Generated by Django 2.2 on 2021-07-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='entered_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
