# Generated by Django 2.2 on 2021-07-21 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0002_remove_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='group_app.User'),
            preserve_default=False,
        ),
    ]
