# Generated by Django 2.2 on 2021-07-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0003_subscription_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='notes',
        ),
    ]
