# Generated by Django 2.2 on 2021-07-29 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0005_auto_20210725_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 29, 8, 23, 57, 67183, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='price_change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
