# Generated by Django 2.2 on 2021-07-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0005_auto_20210725_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='price_change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
