# Generated by Django 2.2 on 2021-07-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0006_auto_20210729_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='placed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
