# Generated by Django 2.2 on 2021-07-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0007_auto_20210729_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msg_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='group_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmt_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='group_app.Message')),
                ('cmt_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='group_app.User')),
            ],
        ),
    ]
