# Generated by Django 2.2 on 2021-07-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0008_comment_message'),
        ('group_app', '0006_auto_20210729_0147'),
    ]

    operations = [
    ]
